//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TortugasProekt.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishOrder
    {
        public int ID { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<int> IDDish { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
